<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-QBC6F12R" ignored="4" name="Default test" tests="1" failures="1" timestamp="26 Jul 2020 23:47:11 GMT" time="131.725" errors="0">
  <testcase name="TC_049_Verify_Billing_Address_field" time="105.572" classname="com.zyto.test.TestCases.Payment_Method_Test">
    <failure type="java.lang.AssertionError" message="[1;91mError message is  not  displayed for invalid details[0m">
      <![CDATA[java.lang.AssertionError: [1;91mError message is  not  displayed for invalid details[0m
at org.testng.Assert.fail(Assert.java:96)
at com.zyto.test.TestCases.Payment_Method_Test.TC_049_Verify_Billing_Address_field(Payment_Method_Test.java:183)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_049_Verify_Billing_Address_field -->
  <testcase name="TC_050_Verify_State_Province_field" time="0.0" classname="com.zyto.test.TestCases.Payment_Method_Test">
    <ignored/>
  </testcase> <!-- TC_050_Verify_State_Province_field -->
  <testcase name="TC_047_Verify_mandate_fields" time="0.0" classname="com.zyto.test.TestCases.Payment_Method_Test">
    <ignored/>
  </testcase> <!-- TC_047_Verify_mandate_fields -->
  <testcase name="TC_046_Verify_billing_address" time="0.0" classname="com.zyto.test.TestCases.Payment_Method_Test">
    <ignored/>
  </testcase> <!-- TC_046_Verify_billing_address -->
  <testcase name="TC_048_Verify_fields_with_invalid_details" time="0.0" classname="com.zyto.test.TestCases.Payment_Method_Test">
    <ignored/>
  </testcase> <!-- TC_048_Verify_fields_with_invalid_details -->
</testsuite> <!-- Default test -->
