<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="4" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="131725" started-at="2020-07-26T23:44:59Z" finished-at="2020-07-26T23:47:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="131725" started-at="2020-07-26T23:44:59Z" finished-at="2020-07-26T23:47:11Z">
      <class name="com.zyto.test.TestCases.Payment_Method_Test">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.zyto.test.TestCases.Payment_Method_Test@5ab9e72c]" name="SetUp" is-config="true" duration-ms="25294" started-at="2020-07-26T23:44:59Z" finished-at="2020-07-26T23:45:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="TC_049_Verify_Billing_Address_field()[pri:0, instance:com.zyto.test.TestCases.Payment_Method_Test@5ab9e72c]" name="TC_049_Verify_Billing_Address_field" duration-ms="105572" started-at="2020-07-26T23:45:25Z" description="To To Verify without filling the data in Billing information fields" finished-at="2020-07-26T23:47:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[1;91mError message is  not  displayed for invalid details[0m]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [1;91mError message is  not  displayed for invalid details[0m
at org.testng.Assert.fail(Assert.java:96)
at com.zyto.test.TestCases.Payment_Method_Test.TC_049_Verify_Billing_Address_field(Payment_Method_Test.java:183)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_049_Verify_Billing_Address_field -->
        <test-method status="PASS" signature="EndTest()[pri:0, instance:com.zyto.test.TestCases.Payment_Method_Test@5ab9e72c]" name="EndTest" is-config="true" duration-ms="672" started-at="2020-07-26T23:47:10Z" finished-at="2020-07-26T23:47:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
      </class> <!-- com.zyto.test.TestCases.Payment_Method_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
